url_shortener/models.py
from .extensions import db
from datetime import datetime
import string
from random import choices

class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(3), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_url()
    
    def generate_short_url(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=3))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_short_url()
        return short_url

url_shortener/__init__.py
from flask import Flask
from .extensions import db
from .routes import short

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(short)

    return app

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .extensions import db
from .models import Link

short = Blueprint('short', __name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits = link.visits + 1
    db.session.commit()

    return redirect(link.original_url)

@short.route('/')
def index():
    return render_template('index.html')

@short.route('/add_link', methods=['POST'])
def add_link():
    original_url = request.form['original_url']  
    link = Link(original_url=original_url) 
    db.session.add(link)
    db.session.commit()

    qr_code = f"https://api.qrserver.com/v1/create-qr-code/?data=http://127.0.0.1:5000/{link.short_url}&size=200x200"
    
    return render_template('link_added.html', 
        new_link=link.short_url, original_url=link.original_url, qr_code=qr_code)

@short.route('/stats')
def stats():
    links = Link.query.all()

    return render_template('stats.html', links=links)

@short.errorhandler(404)
def page_not_found(e):
    return '', 404

url_shortener/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='responsive.css') }}"
    />
    <link rel="icon" href="static/assets/logo.png" />
    <title>Tinify - URL shortener</title>
  </head>
  <body class="index-body">
    <!-- Header -->
    <header class="header">
      <div>
        <img
          class="header-logo"
          src="static/assets/logo.svg"
          alt="Tinify Logo"
        />
      </div>
      <div class="center-header">
        <h1><a href="/">Tinify</a></h1>
        <p>Shorten your URLs with just one click!</p>
      </div>
      <div class="menu">
        <img src="static/assets/menu.svg" alt="Menu" class="menu-inner" />
      </div>
      <div class="links">
        <a href="#">About</a>
        <a href="#">History</a>
      </div>
    </header>

    <!-- Hero section -->
    <main class="hero">
      <!-- Input form -->
      <div class="form">
        <form
          action="{{ url_for('short.add_link') }}"
          method="post"
          id="main-form"
        >
          <input
            type="url"
            name="original_url"
            autocomplete="off"
            placeholder="Enter your ulr..."
            required
          />
        </form>
        <button type="submit" form="main-form" class="submit-button">
          Shorten
          <img class="link-logo" src="static/assets/link-icon.svg" />
        </button>
      </div>

      <!-- About cards -->
      <section class="cards-container">
        <div class="card">
          <h3>Speed</h3>
          <p>We offer a high performance app, optimized for speed quality.</p>
        </div>
        <div class="card">
          <h3>Simplicity</h3>
          <p>
            Tinify is a user-friendly app, aimed to be easely usable by
            everyone.
          </p>
        </div>
        <div class="card">
          <h3>Quality</h3>
          <p>We offer a high quality product aimed to accustom your needs.</p>
        </div>
      </section>
    </main>

    <!-- Footer -->
    <footer class="footer">
      <p>&copy; Tinify - Copyright 2021</p>
      <p class="bottom">
        This project is open source and hosted on
        <a href="https://github.com/Frakko/Tinify">GitHub</a>.
      </p>
    </footer>
  </body>
</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='responsive.css') }}"
    />
    <link rel="icon" href="static/assets/logo.png" />
    <title>URL Shortener</title>
  </head>
  <body>
    <!-- Header -->
    <header class="header">
      <div>
        <img
          class="header-logo"
          src="static/assets/logo.svg"
          alt="Tinify Logo"
        />
      </div>
      <div class="center-header">
        <h1><a href="/">Tinify</a></h1>
        <p>Shorten your URLs with just one click!</p>
      </div>
      <div class="menu">
        <img src="static/assets/menu.svg" alt="Menu" class="menu-inner" />
      </div>
      <div class="links">
        <a href="#">About</a>
        <a href="#">History</a>
      </div>
    </header>

    <!-- Hero section -->
    <main class="hero">
      <!-- Shortened link -->
      <div class="result">
        <div class="display-link">
          <p id="to-cp">
            {{ url_for('short.redirect_to_url', short_url=new_link,
            _external=True) }}
          </p>
        </div>
        <div class="copy-button-container">
          <button class="copy-button" onclick="copyText()">
            Copy
            <img class="copy-logo" src="static/assets/link-icon.svg" />
          </button>
        </div>
      </div>
      <p class="description">
        Directly copy the URL above or scan the QR code below!
      </p>
      <!-- QR code -->
      <div class="img-container">
        <img style="text-align: center" src="{{ qr_code }}" alt="QR-Code" />
      </div>
    </main>

    <!-- Footer -->
    <footer class="footer" id="footer-rp">
      <p>&copy; Tinify - Copyright 2021</p>
      <p class="bottom">
        This project is open source and hosted on
        <a href="https://github.com/Frakko/Tinify">GitHub</a>.
      </p>
    </footer>

    <script src="{{ url_for('static', filename='main.js') }}"></script>
  </body>
</html>

url_shortener/templates/stats.html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>

  <body>
    <table class="content-table">
      <thead>
        <tr>
          <th>Original URL</th>
          <th>Short URL</th>
          <th>Visits</th>
        </tr>
      </thead>
      <tbody>
        {% for link in links %}
        <tr>
          <td>{{ link.original_url }}</td>
          <td>{{ link.short_url }}</td>
          <td>{{ link.visits }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>